=== korea-doko/Craft-Proj/Assets/Resources/XML/AmuletImplicitMod.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="AmuletImplicitMod" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="AmuletImplicitMod">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="GivenID" index-key="GivenID " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="PrimaryKey" index-key="ID " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAABQSnKAePTkQqErmxStruffAAAAAKYwUil9/ORAAAAAAAAAAABBAG0A
dQBsAGUAdABJAG0AcABsAGkAYwBpAHQATQBvAGQAAAAAAAAAgvpHIHtm+EeuY3hf
PC1nbQcAAABQSnKAePTkQqErmxStruffSQBEAAAAAAAAAK3eKsYH3wdJp2ZnW829
thoHAAAAUEpygHj05EKhK5sUra7n30cAaQB2AGUAbgBJAEQAAAAAAAAAnU0Q7bfE
IEOPvunkeS2bmQcAAABQSnKAePTkQqErmxStruffTQBpAG4AVgBhAGwAdQBlAAAA
AAAAAGTMj4wTIfVFi15GnIDIGKkHAAAAUEpygHj05EKhK5sUra7n300AYQB4AFYA
YQBsAHUAZQAAAAAAAABbQoQL1hQvQYYlhV0oaeYxBwAAAFBKcoB49ORCoSubFK2u
599MAGUAdgBlAGwAAAAAAAAAb/TAhR+J4k2zmLmFz+9lxQAAAABtnMSBe/zkQAAA
AAAAAAAATQBvAGQAVAB5AHAAZQAAAAAAAABnbCN9ujtNQJomHwPrx842BwAAAG/0
wIUfieJNs5i5hc/vZcVJAEQAAAAAAAAAw85Z3LZ7AEaaK+KyI9HveQcAAADioPCl
cFBwQ7paqavaTTsiTQBvAGQAVAB5AHAAZQAAAAAAAAAB5aUov1FeQLLaG+fyEodD
BwAAAFBKcoB49ORCoSubFK2u599NAG8AZABUAHkAcABlAAAAAAAAAKnsktP9HLdF
gEAXLOf6mGgHAAAAUEpygHj05EKhK5sUra7n300AbwBkAE4AYQBtAGUAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAwAAAAFAAAAAAAAAAAAAAAAAAAAAAA=
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="95"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="3"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="0"/>
<od:tableProperty name="GUID" type="9" value="UEpygHj05EKhK5sUra7n3w==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="ID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="gvpHIHtm+EeuY3hfPC1nbQ==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="GivenID" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="rd4qxgffB0mnZmdbzb22Gg==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="MinValue" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2220"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="nU0Q7bfEIEOPvunkeS2bmQ==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="MaxValue" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2475"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="ZMyPjBMh9UWLXkacgMgYqQ==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Level" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="W0KEC9YUL0GGJYVdKGnmMQ==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="ModType" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="4515"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="111"/>
<od:fieldProperty name="RowSourceType" type="10" value="Table/Query"/>
<od:fieldProperty name="RowSource" type="12" value="SELECT [ModType].[ID], [ModType].[Type] FROM ModType; "/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="2"/>
<od:fieldProperty name="ColumnHeads" type="1" value="0"/>
<od:fieldProperty name="ColumnWidths" type="10" value="0;1440"/>
<od:fieldProperty name="ListRows" type="3" value="16"/>
<od:fieldProperty name="ListWidth" type="10" value="1440트윕"/>
<od:fieldProperty name="LimitToList" type="1" value="1"/>
<od:fieldProperty name="AllowMultipleValues" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="1"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="AeWlKL9RXkCy2hvn8hKHQw==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="ModName" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="10"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="qeyS0/0ct0WAQBcs5/qYaA==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== korea-doko/Craft-Proj/Assets/Resources/XML/AmuletImplicitMod.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="AmuletImplicitMod.xsd" generated="2017-09-01T21:58:04">
<AmuletImplicitMod>
<ID>1</ID>
<GivenID>-1</GivenID>
<MinValue>0</MinValue>
<MaxValue>0</MaxValue>
<Level>1</Level>
<ModType>8</ModType>
<ModName>없음</ModName>
</AmuletImplicitMod>
<AmuletImplicitMod>
<ID>2</ID>
<GivenID>0</GivenID>
<MinValue>5</MinValue>
<MaxValue>10</MaxValue>
<Level>1</Level>
<ModType>8</ModType>
<ModName>아뮬렛옵1</ModName>
</AmuletImplicitMod>
<AmuletImplicitMod>
<ID>3</ID>
<GivenID>1</GivenID>
<MinValue>5</MinValue>
<MaxValue>10</MaxValue>
<Level>1</Level>
<ModType>11</ModType>
<ModName>아뮬렛옵2</ModName>
</AmuletImplicitMod>
<AmuletImplicitMod>
<ID>4</ID>
<GivenID>2</GivenID>
<MinValue>5</MinValue>
<MaxValue>10</MaxValue>
<Level>1</Level>
<ModType>14</ModType>
<ModName>아뮬렛옵3</ModName>
</AmuletImplicitMod>
<AmuletImplicitMod>
<ID>5</ID>
<GivenID>3</GivenID>
<MinValue>5</MinValue>
<MaxValue>10</MaxValue>
<Level>1</Level>
<ModType>16</ModType>
<ModName>아뮬렛옵4</ModName>
</AmuletImplicitMod>
<AmuletImplicitMod>
<ID>6</ID>
<GivenID>4</GivenID>
<MinValue>50</MinValue>
<MaxValue>100</MaxValue>
<Level>1</Level>
<ModType>6</ModType>
<ModName>아뮬렛옵5</ModName>
</AmuletImplicitMod>
<AmuletImplicitMod>
<ID>7</ID>
<GivenID>5</GivenID>
<MinValue>50</MinValue>
<MaxValue>100</MaxValue>
<Level>1</Level>
<ModType>3</ModType>
<ModName>아뮬렛옵6</ModName>
</AmuletImplicitMod>
<AmuletImplicitMod>
<ID>8</ID>
<GivenID>6</GivenID>
<MinValue>50</MinValue>
<MaxValue>100</MaxValue>
<Level>1</Level>
<ModType>3</ModType>
<ModName>아뮬렛옵7</ModName>
</AmuletImplicitMod>
<AmuletImplicitMod>
<ID>9</ID>
<GivenID>7</GivenID>
<MinValue>50</MinValue>
<MaxValue>100</MaxValue>
<Level>1</Level>
<ModType>12</ModType>
<ModName>아뮬렛옵8</ModName>
</AmuletImplicitMod>
</dataroot>
