=== korea-doko/Craft-Proj/Assets/Resources/XML/BodyArmor.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="BodyArmor" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="BodyArmor">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="GivenID" index-key="GivenID " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="PrimaryKey" index-key="ID " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAADVgaU4egBrSp5hkYjLcI9rAAAAADp7triT++RAAAAAAAAAAABBAHIA
bQBvAHIAAAAAAAAAQ006Iq9iMEq58X7u6u89TwcAAADVgaU4egBrSp5hkYjLcI9r
SQBEAAAAAAAAAL4AnLVLJj9Jlrr55Hw55cYHAAAA1YGlOHoAa0qeYZGIy3CPa0cA
aQB2AGUAbgBJAEQAAAAAAAAA1T6kc06pqUiUQ1Lj/txXkwcAAADVgaU4egBrSp5h
kYjLcI9rTABlAHYAZQBsAAAAAAAAAFKCyquIfrhBgXcKQLs+FbYHAAAA1YGlOHoA
a0qeYZGIy3CPa0EAcgBtAG8AcgAAAAAAAACzLjsG1JKGRbocTymT0kSABwAAANWB
pTh6AGtKnmGRiMtwj2tFAHYAYQBzAGkAbwBuAFIAYQB0AGkAbgBnAAAAAAAAAOYZ
vqNIynpPu91Zh8Y/m1UHAAAA1YGlOHoAa0qeYZGIy3CPa0UAbgBlAHIAZwB5AFMA
aABpAGUAbABkAAAAAAAAAPi4uoqgO8xLjJTIf6hwLH8HAAAA1YGlOHoAa0qeYZGI
y3CPa1IAZQBxAHUAaQByAGUAZABTAHQAcgAAAAAAAADUwGkTamtJT5xBRNqMwLUZ
BwAAANWBpTh6AGtKnmGRiMtwj2tSAGUAcQB1AGkAcgBlAGQARABlAHgAAAAAAAAA
K7mO3ePb40e4edcqg7vDxQcAAADVgaU4egBrSp5hkYjLcI9rUgBlAHEAdQBpAHIA
ZQBkAEkAbgB0AAAAAAAAAHf2iIiPJdJLp+H3KFVOKx0HAAAA1YGlOHoAa0qeYZGI
y3CPa0kAdABlAG0ATgBhAG0AZQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAUA
AAAAAAAAAAAAAAAAAAAAAA==
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="95"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="3"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="0"/>
<od:tableProperty name="GUID" type="9" value="1YGlOHoAa0qeYZGIy3CPaw==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="ID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="Q006Iq9iMEq58X7u6u89Tw==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="GivenID" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="vgCctUsmP0mWuvnkfDnlxg==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Level" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="1T6kc06pqUiUQ1Lj/txXkw==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Armor" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="UoLKq4h+uEGBdwpAuz4Vtg==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="EvasionRating" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="1920"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="sy47BtSShkW6HE8pk9JEgA==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="EnergyShield" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="1815"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="5hm+o0jKek+73VmHxj+bVQ==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="RequiredStr" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="1740"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="+Li6iqA7zEuMlMh/qHAsfw==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="RequiredDex" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2265"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="1MBpE2prSU+cQUTajMC1GQ==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="RequiredInt" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="1635"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="K7mO3ePb40e4edcqg7vDxQ==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="ItemName" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="10"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="d/aIiI8l0kun4fcoVU4rHQ==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== korea-doko/Craft-Proj/Assets/Resources/XML/BodyArmor.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="BodyArmor.xsd" generated="2017-08-25T15:44:56">
<BodyArmor>
<ID>1</ID>
<GivenID>0</GivenID>
<Level>1</Level>
<Armor>60</Armor>
<EvasionRating>0</EvasionRating>
<EnergyShield>0</EnergyShield>
<RequiredStr>1</RequiredStr>
<RequiredDex>0</RequiredDex>
<RequiredInt>0</RequiredInt>
<ItemName>아머1</ItemName>
</BodyArmor>
<BodyArmor>
<ID>2</ID>
<GivenID>1</GivenID>
<Level>3</Level>
<Armor>0</Armor>
<EvasionRating>60</EvasionRating>
<EnergyShield>0</EnergyShield>
<RequiredStr>2</RequiredStr>
<RequiredDex>0</RequiredDex>
<RequiredInt>0</RequiredInt>
<ItemName>아머12</ItemName>
</BodyArmor>
<BodyArmor>
<ID>3</ID>
<GivenID>2</GivenID>
<Level>3</Level>
<Armor>0</Armor>
<EvasionRating>0</EvasionRating>
<EnergyShield>60</EnergyShield>
<RequiredStr>3</RequiredStr>
<RequiredDex>0</RequiredDex>
<RequiredInt>0</RequiredInt>
<ItemName>아머13</ItemName>
</BodyArmor>
<BodyArmor>
<ID>4</ID>
<GivenID>3</GivenID>
<Level>5</Level>
<Armor>100</Armor>
<EvasionRating>0</EvasionRating>
<EnergyShield>0</EnergyShield>
<RequiredStr>0</RequiredStr>
<RequiredDex>1</RequiredDex>
<RequiredInt>0</RequiredInt>
<ItemName>아머14</ItemName>
</BodyArmor>
<BodyArmor>
<ID>5</ID>
<GivenID>4</GivenID>
<Level>5</Level>
<Armor>0</Armor>
<EvasionRating>100</EvasionRating>
<EnergyShield>0</EnergyShield>
<RequiredStr>0</RequiredStr>
<RequiredDex>2</RequiredDex>
<RequiredInt>0</RequiredInt>
<ItemName>아머15</ItemName>
</BodyArmor>
<BodyArmor>
<ID>6</ID>
<GivenID>5</GivenID>
<Level>8</Level>
<Armor>0</Armor>
<EvasionRating>150</EvasionRating>
<EnergyShield>0</EnergyShield>
<RequiredStr>0</RequiredStr>
<RequiredDex>3</RequiredDex>
<RequiredInt>0</RequiredInt>
<ItemName>아머16</ItemName>
</BodyArmor>
<BodyArmor>
<ID>7</ID>
<GivenID>6</GivenID>
<Level>8</Level>
<Armor>0</Armor>
<EvasionRating>0</EvasionRating>
<EnergyShield>240</EnergyShield>
<RequiredStr>0</RequiredStr>
<RequiredDex>0</RequiredDex>
<RequiredInt>1</RequiredInt>
<ItemName>아머17</ItemName>
</BodyArmor>
<BodyArmor>
<ID>8</ID>
<GivenID>7</GivenID>
<Level>8</Level>
<Armor>0</Armor>
<EvasionRating>0</EvasionRating>
<EnergyShield>300</EnergyShield>
<RequiredStr>0</RequiredStr>
<RequiredDex>0</RequiredDex>
<RequiredInt>2</RequiredInt>
<ItemName>아머18</ItemName>
</BodyArmor>
<BodyArmor>
<ID>9</ID>
<GivenID>8</GivenID>
<Level>12</Level>
<Armor>450</Armor>
<EvasionRating>0</EvasionRating>
<EnergyShield>0</EnergyShield>
<RequiredStr>0</RequiredStr>
<RequiredDex>0</RequiredDex>
<RequiredInt>3</RequiredInt>
<ItemName>아머19</ItemName>
</BodyArmor>
<BodyArmor>
<ID>10</ID>
<GivenID>9</GivenID>
<Level>18</Level>
<Armor>50</Armor>
<EvasionRating>50</EvasionRating>
<EnergyShield>50</EnergyShield>
<RequiredStr>4</RequiredStr>
<RequiredDex>0</RequiredDex>
<RequiredInt>0</RequiredInt>
<ItemName>아머120</ItemName>
</BodyArmor>
<BodyArmor>
<ID>11</ID>
<GivenID>10</GivenID>
<Level>19</Level>
<Armor>800</Armor>
<EvasionRating>0</EvasionRating>
<EnergyShield>0</EnergyShield>
<RequiredStr>5</RequiredStr>
<RequiredDex>0</RequiredDex>
<RequiredInt>0</RequiredInt>
<ItemName>아머121</ItemName>
</BodyArmor>
<BodyArmor>
<ID>12</ID>
<GivenID>11</GivenID>
<Level>24</Level>
<Armor>0</Armor>
<EvasionRating>800</EvasionRating>
<EnergyShield>0</EnergyShield>
<RequiredStr>6</RequiredStr>
<RequiredDex>0</RequiredDex>
<RequiredInt>0</RequiredInt>
<ItemName>아머122</ItemName>
</BodyArmor>
<BodyArmor>
<ID>13</ID>
<GivenID>12</GivenID>
<Level>28</Level>
<Armor>0</Armor>
<EvasionRating>0</EvasionRating>
<EnergyShield>800</EnergyShield>
<RequiredStr>0</RequiredStr>
<RequiredDex>7</RequiredDex>
<RequiredInt>0</RequiredInt>
<ItemName>아머123</ItemName>
</BodyArmor>
<BodyArmor>
<ID>14</ID>
<GivenID>13</GivenID>
<Level>32</Level>
<Armor>800</Armor>
<EvasionRating>200</EvasionRating>
<EnergyShield>0</EnergyShield>
<RequiredStr>0</RequiredStr>
<RequiredDex>8</RequiredDex>
<RequiredInt>0</RequiredInt>
<ItemName>아머124</ItemName>
</BodyArmor>
<BodyArmor>
<ID>15</ID>
<GivenID>14</GivenID>
<Level>36</Level>
<Armor>100</Armor>
<EvasionRating>800</EvasionRating>
<EnergyShield>0</EnergyShield>
<RequiredStr>0</RequiredStr>
<RequiredDex>9</RequiredDex>
<RequiredInt>0</RequiredInt>
<ItemName>아머125</ItemName>
</BodyArmor>
<BodyArmor>
<ID>16</ID>
<GivenID>15</GivenID>
<Level>42</Level>
<Armor>100</Armor>
<EvasionRating>500</EvasionRating>
<EnergyShield>400</EnergyShield>
<RequiredStr>0</RequiredStr>
<RequiredDex>0</RequiredDex>
<RequiredInt>9</RequiredInt>
<ItemName>아머126</ItemName>
</BodyArmor>
<BodyArmor>
<ID>17</ID>
<GivenID>16</GivenID>
<Level>49</Level>
<Armor>800</Armor>
<EvasionRating>0</EvasionRating>
<EnergyShield>400</EnergyShield>
<RequiredStr>0</RequiredStr>
<RequiredDex>0</RequiredDex>
<RequiredInt>8</RequiredInt>
<ItemName>아머127</ItemName>
</BodyArmor>
<BodyArmor>
<ID>18</ID>
<GivenID>17</GivenID>
<Level>56</Level>
<Armor>0</Armor>
<EvasionRating>1200</EvasionRating>
<EnergyShield>0</EnergyShield>
<RequiredStr>0</RequiredStr>
<RequiredDex>0</RequiredDex>
<RequiredInt>7</RequiredInt>
<ItemName>아머128</ItemName>
</BodyArmor>
<BodyArmor>
<ID>19</ID>
<GivenID>18</GivenID>
<Level>60</Level>
<Armor>1200</Armor>
<EvasionRating>0</EvasionRating>
<EnergyShield>0</EnergyShield>
<RequiredStr>0</RequiredStr>
<RequiredDex>10</RequiredDex>
<RequiredInt>0</RequiredInt>
<ItemName>아머129</ItemName>
</BodyArmor>
<BodyArmor>
<ID>20</ID>
<GivenID>19</GivenID>
<Level>62</Level>
<Armor>0</Armor>
<EvasionRating>0</EvasionRating>
<EnergyShield>1200</EnergyShield>
<RequiredStr>11</RequiredStr>
<RequiredDex>0</RequiredDex>
<RequiredInt>0</RequiredInt>
<ItemName>아머130</ItemName>
</BodyArmor>
<BodyArmor>
<ID>21</ID>
<GivenID>20</GivenID>
<Level>70</Level>
<Armor>1000</Armor>
<EvasionRating>1000</EvasionRating>
<EnergyShield>1000</EnergyShield>
<RequiredStr>0</RequiredStr>
<RequiredDex>0</RequiredDex>
<RequiredInt>12</RequiredInt>
<ItemName>아머131</ItemName>
</BodyArmor>
</dataroot>
