=== korea-doko/Craft-Proj/Assets/Resources/XML/Boots.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Boots" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="Boots">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="GivenID" index-key="GivenID " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="PrimaryKey" index-key="ID " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
<od:tableProperty name="GUID" type="9" value="rJRaw0lvQ0SeuBZSCiq/Lw==
"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAACslFrDSW9DRJ64FlIKKr8vAAAAACzNNk5+++RAAAAAAAAAAABCAG8A
bwB0AHMAAAAAAAAAYKMhmZpZuEOJEEFfbjtUsAcAAACslFrDSW9DRJ64FlIKKr8v
SQBEAAAAAAAAAFOZKzQJgXRPlk+LIValw9gHAAAArJRaw0lvQ0SeuBZSCiq/L0cA
aQB2AGUAbgBJAEQAAAAAAAAAdQaFcVfoJEOJlQ9wdfxGlAcAAACslFrDSW9DRJ64
FlIKKr8vTABlAHYAZQBsAAAAAAAAAMMZGAmiGSxGjiUm0S8htVgHAAAArJRaw0lv
Q0SeuBZSCiq/L0EAcgBtAG8AcgAAAAAAAAC+muzT+nTHQZbl1G7Gvxd8BwAAAKyU
WsNJb0NEnrgWUgoqvy9FAHYAYQBzAGkAbwBuAFIAYQB0AGkAbgBnAAAAAAAAAMAu
ON9+tR9AlUfvpUn+x28HAAAArJRaw0lvQ0SeuBZSCiq/L0UAbgBlAHIAZwB5AFMA
aABpAGUAbABkAAAAAAAAAMkt4SxPyc5DkAvj/EmGqpsHAAAArJRaw0lvQ0SeuBZS
Ciq/L1IAZQBxAHUAaQByAGUAZABTAHQAcgAAAAAAAABSH0i58mS7SrYpNTCp3aSn
BwAAAKyUWsNJb0NEnrgWUgoqvy9SAGUAcQB1AGkAcgBlAGQARABlAHgAAAAAAAAA
fYY6KNAR7Um+a3UXewHQiQcAAACslFrDSW9DRJ64FlIKKr8vUgBlAHEAdQBpAHIA
ZQBkAEkAbgB0AAAAAAAAAH36YEeDiJ1LjPj8RtEJpXkHAAAArJRaw0lvQ0SeuBZS
Ciq/L0kAdABlAG0ATgBhAG0AZQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAUA
AAAAAAAAAAAAAAAAAAAAAA==
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="95"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="3"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="ID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="YKMhmZpZuEOJEEFfbjtUsA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="GivenID" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="U5krNAmBdE+WT4shVqXD2A==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="2"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Level" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="dQaFcVfoJEOJlQ9wdfxGlA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="4"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Armor" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="wxkYCaIZLEaOJSbRLyG1WA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="5"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="EvasionRating" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="vprs0/p0x0GW5dRuxr8XfA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="1920"/>
<od:fieldProperty name="ColumnOrder" type="3" value="6"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="EnergyShield" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="wC443361H0CVR++lSf7Hbw==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="1815"/>
<od:fieldProperty name="ColumnOrder" type="3" value="7"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="RequiredStr" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="yS3hLE/JzkOQC+P8SYaqmw==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="1740"/>
<od:fieldProperty name="ColumnOrder" type="3" value="8"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="RequiredDex" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="Uh9IufJku0q2KTUwqd2kpw==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="2265"/>
<od:fieldProperty name="ColumnOrder" type="3" value="9"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="RequiredInt" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="fYY6KNAR7Um+a3UXewHQiQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="1635"/>
<od:fieldProperty name="ColumnOrder" type="3" value="10"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="ItemName" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="ffpgR4OInUuM+PxG0QmleQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="3"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="10"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== korea-doko/Craft-Proj/Assets/Resources/XML/Boots.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Boots.xsd" generated="2017-08-24T22:59:19">
<Boots>
<ID>1</ID>
<GivenID>0</GivenID>
<Level>1</Level>
<Armor>60</Armor>
<EvasionRating>0</EvasionRating>
<EnergyShield>0</EnergyShield>
<RequiredStr>1</RequiredStr>
<RequiredDex>0</RequiredDex>
<RequiredInt>0</RequiredInt>
<ItemName>아이언 그레이브즈</ItemName>
</Boots>
<Boots>
<ID>2</ID>
<GivenID>1</GivenID>
<Level>3</Level>
<Armor>0</Armor>
<EvasionRating>60</EvasionRating>
<EnergyShield>0</EnergyShield>
<RequiredStr>2</RequiredStr>
<RequiredDex>0</RequiredDex>
<RequiredInt>0</RequiredInt>
<ItemName>울 슈즈</ItemName>
</Boots>
<Boots>
<ID>3</ID>
<GivenID>2</GivenID>
<Level>3</Level>
<Armor>0</Armor>
<EvasionRating>0</EvasionRating>
<EnergyShield>60</EnergyShield>
<RequiredStr>3</RequiredStr>
<RequiredDex>0</RequiredDex>
<RequiredInt>0</RequiredInt>
<ItemName>로하이드 부츠</ItemName>
</Boots>
<Boots>
<ID>4</ID>
<GivenID>3</GivenID>
<Level>5</Level>
<Armor>100</Armor>
<EvasionRating>0</EvasionRating>
<EnergyShield>0</EnergyShield>
<RequiredStr>0</RequiredStr>
<RequiredDex>1</RequiredDex>
<RequiredInt>0</RequiredInt>
<ItemName>체인 부츠</ItemName>
</Boots>
<Boots>
<ID>5</ID>
<GivenID>4</GivenID>
<Level>5</Level>
<Armor>0</Armor>
<EvasionRating>100</EvasionRating>
<EnergyShield>0</EnergyShield>
<RequiredStr>0</RequiredStr>
<RequiredDex>2</RequiredDex>
<RequiredInt>0</RequiredInt>
<ItemName>랩드 부츠</ItemName>
</Boots>
<Boots>
<ID>6</ID>
<GivenID>5</GivenID>
<Level>8</Level>
<Armor>0</Armor>
<EvasionRating>150</EvasionRating>
<EnergyShield>0</EnergyShield>
<RequiredStr>0</RequiredStr>
<RequiredDex>3</RequiredDex>
<RequiredInt>0</RequiredInt>
<ItemName>레더 스케일 부츠</ItemName>
</Boots>
<Boots>
<ID>7</ID>
<GivenID>6</GivenID>
<Level>8</Level>
<Armor>0</Armor>
<EvasionRating>0</EvasionRating>
<EnergyShield>240</EnergyShield>
<RequiredStr>0</RequiredStr>
<RequiredDex>0</RequiredDex>
<RequiredInt>1</RequiredInt>
<ItemName>벨벳 슬리퍼</ItemName>
</Boots>
<Boots>
<ID>8</ID>
<GivenID>7</GivenID>
<Level>8</Level>
<Armor>0</Armor>
<EvasionRating>0</EvasionRating>
<EnergyShield>300</EnergyShield>
<RequiredStr>0</RequiredStr>
<RequiredDex>0</RequiredDex>
<RequiredInt>2</RequiredInt>
<ItemName>스틸 그레이브즈</ItemName>
</Boots>
<Boots>
<ID>9</ID>
<GivenID>8</GivenID>
<Level>12</Level>
<Armor>450</Armor>
<EvasionRating>0</EvasionRating>
<EnergyShield>0</EnergyShield>
<RequiredStr>0</RequiredStr>
<RequiredDex>0</RequiredDex>
<RequiredInt>3</RequiredInt>
<ItemName>고트하이드 부츠</ItemName>
</Boots>
<Boots>
<ID>10</ID>
<GivenID>9</GivenID>
<Level>18</Level>
<Armor>50</Armor>
<EvasionRating>50</EvasionRating>
<EnergyShield>50</EnergyShield>
<RequiredStr>4</RequiredStr>
<RequiredDex>0</RequiredDex>
<RequiredInt>0</RequiredInt>
<ItemName>링메일 부츠</ItemName>
</Boots>
<Boots>
<ID>11</ID>
<GivenID>10</GivenID>
<Level>19</Level>
<Armor>800</Armor>
<EvasionRating>0</EvasionRating>
<EnergyShield>0</EnergyShield>
<RequiredStr>5</RequiredStr>
<RequiredDex>0</RequiredDex>
<RequiredInt>0</RequiredInt>
<ItemName>스트랩 부츠</ItemName>
</Boots>
<Boots>
<ID>12</ID>
<GivenID>11</GivenID>
<Level>24</Level>
<Armor>0</Armor>
<EvasionRating>800</EvasionRating>
<EnergyShield>0</EnergyShield>
<RequiredStr>6</RequiredStr>
<RequiredDex>0</RequiredDex>
<RequiredInt>0</RequiredInt>
<ItemName>아이언 스케일 부츠</ItemName>
</Boots>
<Boots>
<ID>13</ID>
<GivenID>12</GivenID>
<Level>28</Level>
<Armor>0</Armor>
<EvasionRating>0</EvasionRating>
<EnergyShield>800</EnergyShield>
<RequiredStr>0</RequiredStr>
<RequiredDex>7</RequiredDex>
<RequiredInt>0</RequiredInt>
<ItemName>실크 슬리퍼</ItemName>
</Boots>
<Boots>
<ID>14</ID>
<GivenID>13</GivenID>
<Level>32</Level>
<Armor>800</Armor>
<EvasionRating>200</EvasionRating>
<EnergyShield>0</EnergyShield>
<RequiredStr>0</RequiredStr>
<RequiredDex>8</RequiredDex>
<RequiredInt>0</RequiredInt>
<ItemName>디어스킨 부츠</ItemName>
</Boots>
<Boots>
<ID>15</ID>
<GivenID>14</GivenID>
<Level>36</Level>
<Armor>100</Armor>
<EvasionRating>800</EvasionRating>
<EnergyShield>0</EnergyShield>
<RequiredStr>0</RequiredStr>
<RequiredDex>9</RequiredDex>
<RequiredInt>0</RequiredInt>
<ItemName>플레이트 그레이브즈</ItemName>
</Boots>
<Boots>
<ID>16</ID>
<GivenID>15</GivenID>
<Level>42</Level>
<Armor>100</Armor>
<EvasionRating>500</EvasionRating>
<EnergyShield>400</EnergyShield>
<RequiredStr>0</RequiredStr>
<RequiredDex>0</RequiredDex>
<RequiredInt>9</RequiredInt>
<ItemName>클래프스부츠</ItemName>
</Boots>
<Boots>
<ID>17</ID>
<GivenID>16</GivenID>
<Level>49</Level>
<Armor>800</Armor>
<EvasionRating>0</EvasionRating>
<EnergyShield>400</EnergyShield>
<RequiredStr>0</RequiredStr>
<RequiredDex>0</RequiredDex>
<RequiredInt>8</RequiredInt>
<ItemName>메쉬부츠</ItemName>
</Boots>
<Boots>
<ID>18</ID>
<GivenID>17</GivenID>
<Level>56</Level>
<Armor>0</Armor>
<EvasionRating>1200</EvasionRating>
<EnergyShield>0</EnergyShield>
<RequiredStr>0</RequiredStr>
<RequiredDex>0</RequiredDex>
<RequiredInt>7</RequiredInt>
<ItemName>브론즈스케일부츠</ItemName>
</Boots>
<Boots>
<ID>19</ID>
<GivenID>18</GivenID>
<Level>60</Level>
<Armor>1200</Armor>
<EvasionRating>0</EvasionRating>
<EnergyShield>0</EnergyShield>
<RequiredStr>0</RequiredStr>
<RequiredDex>10</RequiredDex>
<RequiredInt>0</RequiredInt>
<ItemName>레인포스드부츠</ItemName>
</Boots>
<Boots>
<ID>20</ID>
<GivenID>19</GivenID>
<Level>62</Level>
<Armor>0</Armor>
<EvasionRating>0</EvasionRating>
<EnergyShield>1200</EnergyShield>
<RequiredStr>11</RequiredStr>
<RequiredDex>0</RequiredDex>
<RequiredInt>0</RequiredInt>
<ItemName>스콜라 부츠</ItemName>
</Boots>
<Boots>
<ID>21</ID>
<GivenID>20</GivenID>
<Level>70</Level>
<Armor>1000</Armor>
<EvasionRating>1000</EvasionRating>
<EnergyShield>1000</EnergyShield>
<RequiredStr>0</RequiredStr>
<RequiredDex>0</RequiredDex>
<RequiredInt>12</RequiredInt>
<ItemName>스틸스케일부츠</ItemName>
</Boots>
</dataroot>
