=== korea-doko/Craft-Proj/Assets/Resources/XML/Dagger.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Dagger" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="Dagger">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="GivenID" index-key="GivenID " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="PrimaryKey" index-key="ID " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAADwis7TC7QtQIqW3zdbUwpHAAAAAIR4waaT++RAAAAAAAAAAABEAGEA
ZwBnAGUAcgAAAAAAAAAQjPXpauAdRa+J0nwiqdiRBwAAAPCKztMLtC1AipbfN1tT
CkdJAEQAAAAAAAAAiQNJZWW31EWchQ6i2wzpaAcAAADwis7TC7QtQIqW3zdbUwpH
RwBpAHYAZQBuAEkARAAAAAAAAADMdcL8WpJYS6VIHrAulVFfBwAAAPCKztMLtC1A
ipbfN1tTCkdMAGUAdgBlAGwAAAAAAAAAf0YrIAAVSk6wBQED3SpOWAcAAADwis7T
C7QtQIqW3zdbUwpHUgBlAHEAdQBpAHIAZQBkAFMAdAByAAAAAAAAAPwumTqNY51D
qOMcgO/o4vYHAAAA8IrO0wu0LUCKlt83W1MKR1IAZQBxAHUAaQByAGUAZABEAGUA
eAAAAAAAAABppm6xC2GUQ703siEyEwI7BwAAAPCKztMLtC1AipbfN1tTCkdSAGUA
cQB1AGkAcgBlAGQASQBuAHQAAAAAAAAAGTsPTdD6OEWHLOuRWmOm5AcAAADwis7T
C7QtQIqW3zdbUwpHQQB0AHQAYQBjAGsAUwBwAGUAZQBkAAAAAAAAABmd6gjFEcNB
olKIVUeQ3KYHAAAA8IrO0wu0LUCKlt83W1MKR00AaQBuAEQAYQBtAGEAZwBlAAAA
AAAAACWJEOwZ2YZHsUTcNB5B590HAAAA8IrO0wu0LUCKlt83W1MKR0kAdABlAG0A
TgBhAG0AZQAAAAAAAAAggiNVYp01QKFeM1+r9rwpBwAAAPCKztMLtC1AipbfN1tT
CkdNAGEAeABEAGEAbQBhAGcAZQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAUA
AAAAAAAAAAAAAAAAAAAAAA==
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="95"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="3"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="0"/>
<od:tableProperty name="GUID" type="9" value="8IrO0wu0LUCKlt83W1MKRw==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="ID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="EIz16WrgHUWvidJ8IqnYkQ==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="GivenID" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="iQNJZWW31EWchQ6i2wzpaA==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Level" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="zHXC/FqSWEulSB6wLpVRXw==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="RequiredStr" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="1830"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="f0YrIAAVSk6wBQED3SpOWA==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="RequiredDex" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="1875"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="/C6ZOo1jnUOo4xyA7+ji9g==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="RequiredInt" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="1740"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="aaZusQthlEO9N7IhMhMCOw==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="AttackSpeed" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="1965"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="GTsPTdD6OEWHLOuRWmOm5A==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="MinDamage" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="1800"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="GZ3qCMURw0GiUohVR5Dcpg==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="ItemName" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="1755"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="10"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="JYkQ7BnZhkexRNw0HkHn3Q==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="MaxDamage" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2055"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="IIIjVWKdNUChXjNfq/a8KQ==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== korea-doko/Craft-Proj/Assets/Resources/XML/Dagger.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Dagger.xsd" generated="2017-08-25T14:54:32">
<Dagger>
<ID>1</ID>
<GivenID>0</GivenID>
<Level>1</Level>
<RequiredStr>8</RequiredStr>
<RequiredDex>8</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>145</AttackSpeed>
<MinDamage>4</MinDamage>
<ItemName>대거1</ItemName>
<MaxDamage>10</MaxDamage>
</Dagger>
<Dagger>
<ID>2</ID>
<GivenID>1</GivenID>
<Level>5</Level>
<RequiredStr>14</RequiredStr>
<RequiredDex>14</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>140</AttackSpeed>
<MinDamage>7</MinDamage>
<ItemName>대거2</ItemName>
<MaxDamage>15</MaxDamage>
</Dagger>
<Dagger>
<ID>3</ID>
<GivenID>2</GivenID>
<Level>10</Level>
<RequiredStr>18</RequiredStr>
<RequiredDex>26</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>155</AttackSpeed>
<MinDamage>5</MinDamage>
<ItemName>대거3</ItemName>
<MaxDamage>22</MaxDamage>
</Dagger>
<Dagger>
<ID>4</ID>
<GivenID>3</GivenID>
<Level>15</Level>
<RequiredStr>30</RequiredStr>
<RequiredDex>30</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>130</AttackSpeed>
<MinDamage>17</MinDamage>
<ItemName>대거4</ItemName>
<MaxDamage>25</MaxDamage>
</Dagger>
<Dagger>
<ID>5</ID>
<GivenID>4</GivenID>
<Level>20</Level>
<RequiredStr>41</RequiredStr>
<RequiredDex>35</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>120</AttackSpeed>
<MinDamage>20</MinDamage>
<ItemName>대거5</ItemName>
<MaxDamage>37</MaxDamage>
</Dagger>
<Dagger>
<ID>6</ID>
<GivenID>5</GivenID>
<Level>24</Level>
<RequiredStr>44</RequiredStr>
<RequiredDex>44</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>130</AttackSpeed>
<MinDamage>20</MinDamage>
<ItemName>대거6</ItemName>
<MaxDamage>38</MaxDamage>
</Dagger>
<Dagger>
<ID>7</ID>
<GivenID>6</GivenID>
<Level>28</Level>
<RequiredStr>46</RequiredStr>
<RequiredDex>55</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>150</AttackSpeed>
<MinDamage>19</MinDamage>
<ItemName>대거7</ItemName>
<MaxDamage>33</MaxDamage>
</Dagger>
<Dagger>
<ID>8</ID>
<GivenID>7</GivenID>
<Level>32</Level>
<RequiredStr>57</RequiredStr>
<RequiredDex>57</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>130</AttackSpeed>
<MinDamage>28</MinDamage>
<ItemName>대거8</ItemName>
<MaxDamage>54</MaxDamage>
</Dagger>
<Dagger>
<ID>9</ID>
<GivenID>8</GivenID>
<Level>34</Level>
<RequiredStr>64</RequiredStr>
<RequiredDex>64</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>115</AttackSpeed>
<MinDamage>25</MinDamage>
<ItemName>대거9</ItemName>
<MaxDamage>60</MaxDamage>
</Dagger>
<Dagger>
<ID>10</ID>
<GivenID>9</GivenID>
<Level>35</Level>
<RequiredStr>62</RequiredStr>
<RequiredDex>62</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>130</AttackSpeed>
<MinDamage>13</MinDamage>
<ItemName>대거10</ItemName>
<MaxDamage>53</MaxDamage>
</Dagger>
<Dagger>
<ID>11</ID>
<GivenID>10</GivenID>
<Level>38</Level>
<RequiredStr>55</RequiredStr>
<RequiredDex>79</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>155</AttackSpeed>
<MinDamage>37</MinDamage>
<ItemName>대거11</ItemName>
<MaxDamage>53</MaxDamage>
</Dagger>
<Dagger>
<ID>12</ID>
<GivenID>11</GivenID>
<Level>41</Level>
<RequiredStr>72</RequiredStr>
<RequiredDex>72</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>130</AttackSpeed>
<MinDamage>38</MinDamage>
<ItemName>대거12</ItemName>
<MaxDamage>53</MaxDamage>
</Dagger>
<Dagger>
<ID>13</ID>
<GivenID>12</GivenID>
<Level>44</Level>
<RequiredStr>83</RequiredStr>
<RequiredDex>70</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>120</AttackSpeed>
<MinDamage>36</MinDamage>
<ItemName>대거13</ItemName>
<MaxDamage>70</MaxDamage>
</Dagger>
<Dagger>
<ID>14</ID>
<GivenID>13</GivenID>
<Level>47</Level>
<RequiredStr>81</RequiredStr>
<RequiredDex>81</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>130</AttackSpeed>
<MinDamage>34</MinDamage>
<ItemName>대거14</ItemName>
<MaxDamage>66</MaxDamage>
</Dagger>
<Dagger>
<ID>15</ID>
<GivenID>14</GivenID>
<Level>50</Level>
<RequiredStr>78</RequiredStr>
<RequiredDex>94</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>150</AttackSpeed>
<MinDamage>30</MinDamage>
<ItemName>대거15</ItemName>
<MaxDamage>55</MaxDamage>
</Dagger>
<Dagger>
<ID>16</ID>
<GivenID>15</GivenID>
<Level>53</Level>
<RequiredStr>91</RequiredStr>
<RequiredDex>91</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>130</AttackSpeed>
<MinDamage>44</MinDamage>
<ItemName>대거16</ItemName>
<MaxDamage>86</MaxDamage>
</Dagger>
<Dagger>
<ID>17</ID>
<GivenID>16</GivenID>
<Level>55</Level>
<RequiredStr>99</RequiredStr>
<RequiredDex>99</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>115</AttackSpeed>
<MinDamage>39</MinDamage>
<ItemName>대거17</ItemName>
<MaxDamage>94</MaxDamage>
</Dagger>
<Dagger>
<ID>18</ID>
<GivenID>17</GivenID>
<Level>56</Level>
<RequiredStr>96</RequiredStr>
<RequiredDex>96</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>130</AttackSpeed>
<MinDamage>20</MinDamage>
<ItemName>대거18</ItemName>
<MaxDamage>83</MaxDamage>
</Dagger>
<Dagger>
<ID>19</ID>
<GivenID>18</GivenID>
<Level>58</Level>
<RequiredStr>81</RequiredStr>
<RequiredDex>117</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>155</AttackSpeed>
<MinDamage>54</MinDamage>
<ItemName>대거19</ItemName>
<MaxDamage>80</MaxDamage>
</Dagger>
<Dagger>
<ID>20</ID>
<GivenID>19</GivenID>
<Level>60</Level>
<RequiredStr>113</RequiredStr>
<RequiredDex>113</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>130</AttackSpeed>
<MinDamage>53</MinDamage>
<ItemName>대거20</ItemName>
<MaxDamage>78</MaxDamage>
</Dagger>
<Dagger>
<ID>21</ID>
<GivenID>20</GivenID>
<Level>62</Level>
<RequiredStr>122</RequiredStr>
<RequiredDex>104</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>120</AttackSpeed>
<MinDamage>46</MinDamage>
<ItemName>대거21</ItemName>
<MaxDamage>98</MaxDamage>
</Dagger>
<Dagger>
<ID>22</ID>
<GivenID>21</GivenID>
<Level>64</Level>
<RequiredStr>113</RequiredStr>
<RequiredDex>113</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>130</AttackSpeed>
<MinDamage>41</MinDamage>
<ItemName>미드나잇 블레이드</ItemName>
<MaxDamage>86</MaxDamage>
</Dagger>
</dataroot>
