=== korea-doko/Craft-Proj/Assets/Resources/XML/Helmet.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Helmet" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="Helmet">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="GivenID" index-key="GivenID " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="PrimaryKey" index-key="ID " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAAAICEaB8C5CRo/DU2+t14fjAAAAALq7CbiT++RAAAAAAAAAAABIAGUA
bABtAGUAdAAAAAAAAAALLmRMd39mRYfvtOji3mwRBwAAAAgIRoHwLkJGj8NTb63X
h+NJAEQAAAAAAAAAKI8yMnq9KkeFTn2B+RYtywcAAAAICEaB8C5CRo/DU2+t14fj
RwBpAHYAZQBuAEkARAAAAAAAAAD823gond4ASoyuAXsPMbvhBwAAAAgIRoHwLkJG
j8NTb63Xh+NMAGUAdgBlAGwAAAAAAAAA3L6Yb54wEUe1JPWZ7nl25QcAAAAICEaB
8C5CRo/DU2+t14fjQQByAG0AbwByAAAAAAAAAD3OAIyrwCpBljzbYz4Bq4QHAAAA
CAhGgfAuQkaPw1NvrdeH40UAdgBhAHMAaQBvAG4AUgBhAHQAaQBuAGcAAAAAAAAA
WANPGjLP7kOr7ze9wt2OBQcAAAAICEaB8C5CRo/DU2+t14fjRQBuAGUAcgBnAHkA
UwBoAGkAZQBsAGQAAAAAAAAA8AqVZNfYyU+8t+9n1rs2EwcAAAAICEaB8C5CRo/D
U2+t14fjUgBlAHEAdQBpAHIAZQBkAFMAdAByAAAAAAAAAK0nW/epoYNMrGxnbCqJ
O2gHAAAACAhGgfAuQkaPw1NvrdeH41IAZQBxAHUAaQByAGUAZABEAGUAeAAAAAAA
AAA4GPEyaA94RLxvFKTE63DRBwAAAAgIRoHwLkJGj8NTb63Xh+NSAGUAcQB1AGkA
cgBlAGQASQBuAHQAAAAAAAAAinsJ0mWFvk6ASnezKCNlNwcAAAAICEaB8C5CRo/D
U2+t14fjSQB0AGUAbQBOAGEAbQBlAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAA
BQAAAAAAAAAAAAAAAAAAAAAA
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="95"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="3"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="0"/>
<od:tableProperty name="GUID" type="9" value="CAhGgfAuQkaPw1NvrdeH4w==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="ID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="Cy5kTHd/ZkWH77To4t5sEQ==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="GivenID" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="KI8yMnq9KkeFTn2B+RYtyw==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Level" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="/Nt4KJ3eAEqMrgF7DzG74Q==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Armor" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="3L6Yb54wEUe1JPWZ7nl25Q==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="EvasionRating" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="1920"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="Pc4AjKvAKkGWPNtjPgGrhA==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="EnergyShield" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="1815"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="WANPGjLP7kOr7ze9wt2OBQ==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="RequiredStr" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="1740"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="8AqVZNfYyU+8t+9n1rs2Ew==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="RequiredDex" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2265"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="rSdb96mhg0ysbGdsKok7aA==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="RequiredInt" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="1635"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="OBjxMmgPeES8bxSkxOtw0Q==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="ItemName" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="10"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="insJ0mWFvk6ASnezKCNlNw==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== korea-doko/Craft-Proj/Assets/Resources/XML/Helmet.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Helmet.xsd" generated="2017-08-25T14:54:43">
<Helmet>
<ID>1</ID>
<GivenID>0</GivenID>
<Level>1</Level>
<Armor>60</Armor>
<EvasionRating>0</EvasionRating>
<EnergyShield>0</EnergyShield>
<RequiredStr>1</RequiredStr>
<RequiredDex>0</RequiredDex>
<RequiredInt>0</RequiredInt>
<ItemName>헬멧1</ItemName>
</Helmet>
<Helmet>
<ID>2</ID>
<GivenID>1</GivenID>
<Level>3</Level>
<Armor>0</Armor>
<EvasionRating>60</EvasionRating>
<EnergyShield>0</EnergyShield>
<RequiredStr>2</RequiredStr>
<RequiredDex>0</RequiredDex>
<RequiredInt>0</RequiredInt>
<ItemName>헬멧2</ItemName>
</Helmet>
<Helmet>
<ID>3</ID>
<GivenID>2</GivenID>
<Level>3</Level>
<Armor>0</Armor>
<EvasionRating>0</EvasionRating>
<EnergyShield>60</EnergyShield>
<RequiredStr>3</RequiredStr>
<RequiredDex>0</RequiredDex>
<RequiredInt>0</RequiredInt>
<ItemName>헬멧3</ItemName>
</Helmet>
<Helmet>
<ID>4</ID>
<GivenID>3</GivenID>
<Level>5</Level>
<Armor>100</Armor>
<EvasionRating>0</EvasionRating>
<EnergyShield>0</EnergyShield>
<RequiredStr>0</RequiredStr>
<RequiredDex>1</RequiredDex>
<RequiredInt>0</RequiredInt>
<ItemName>헬멧4</ItemName>
</Helmet>
<Helmet>
<ID>5</ID>
<GivenID>4</GivenID>
<Level>5</Level>
<Armor>0</Armor>
<EvasionRating>100</EvasionRating>
<EnergyShield>0</EnergyShield>
<RequiredStr>0</RequiredStr>
<RequiredDex>2</RequiredDex>
<RequiredInt>0</RequiredInt>
<ItemName>헬멧5</ItemName>
</Helmet>
<Helmet>
<ID>6</ID>
<GivenID>5</GivenID>
<Level>8</Level>
<Armor>0</Armor>
<EvasionRating>150</EvasionRating>
<EnergyShield>0</EnergyShield>
<RequiredStr>0</RequiredStr>
<RequiredDex>3</RequiredDex>
<RequiredInt>0</RequiredInt>
<ItemName>헬멧6</ItemName>
</Helmet>
<Helmet>
<ID>7</ID>
<GivenID>6</GivenID>
<Level>8</Level>
<Armor>0</Armor>
<EvasionRating>0</EvasionRating>
<EnergyShield>240</EnergyShield>
<RequiredStr>0</RequiredStr>
<RequiredDex>0</RequiredDex>
<RequiredInt>1</RequiredInt>
<ItemName>헬멧7</ItemName>
</Helmet>
<Helmet>
<ID>8</ID>
<GivenID>7</GivenID>
<Level>8</Level>
<Armor>0</Armor>
<EvasionRating>0</EvasionRating>
<EnergyShield>300</EnergyShield>
<RequiredStr>0</RequiredStr>
<RequiredDex>0</RequiredDex>
<RequiredInt>2</RequiredInt>
<ItemName>헬멧8</ItemName>
</Helmet>
<Helmet>
<ID>9</ID>
<GivenID>8</GivenID>
<Level>12</Level>
<Armor>450</Armor>
<EvasionRating>0</EvasionRating>
<EnergyShield>0</EnergyShield>
<RequiredStr>0</RequiredStr>
<RequiredDex>0</RequiredDex>
<RequiredInt>3</RequiredInt>
<ItemName>헬멧9</ItemName>
</Helmet>
<Helmet>
<ID>10</ID>
<GivenID>9</GivenID>
<Level>18</Level>
<Armor>50</Armor>
<EvasionRating>50</EvasionRating>
<EnergyShield>50</EnergyShield>
<RequiredStr>4</RequiredStr>
<RequiredDex>0</RequiredDex>
<RequiredInt>0</RequiredInt>
<ItemName>헬멧10</ItemName>
</Helmet>
<Helmet>
<ID>11</ID>
<GivenID>10</GivenID>
<Level>19</Level>
<Armor>800</Armor>
<EvasionRating>0</EvasionRating>
<EnergyShield>0</EnergyShield>
<RequiredStr>5</RequiredStr>
<RequiredDex>0</RequiredDex>
<RequiredInt>0</RequiredInt>
<ItemName>헬멧11</ItemName>
</Helmet>
<Helmet>
<ID>12</ID>
<GivenID>11</GivenID>
<Level>24</Level>
<Armor>0</Armor>
<EvasionRating>800</EvasionRating>
<EnergyShield>0</EnergyShield>
<RequiredStr>6</RequiredStr>
<RequiredDex>0</RequiredDex>
<RequiredInt>0</RequiredInt>
<ItemName>헬멧12</ItemName>
</Helmet>
<Helmet>
<ID>13</ID>
<GivenID>12</GivenID>
<Level>28</Level>
<Armor>0</Armor>
<EvasionRating>0</EvasionRating>
<EnergyShield>800</EnergyShield>
<RequiredStr>0</RequiredStr>
<RequiredDex>7</RequiredDex>
<RequiredInt>0</RequiredInt>
<ItemName>헬멧123</ItemName>
</Helmet>
<Helmet>
<ID>14</ID>
<GivenID>13</GivenID>
<Level>32</Level>
<Armor>800</Armor>
<EvasionRating>200</EvasionRating>
<EnergyShield>0</EnergyShield>
<RequiredStr>0</RequiredStr>
<RequiredDex>8</RequiredDex>
<RequiredInt>0</RequiredInt>
<ItemName>헬멧15</ItemName>
</Helmet>
<Helmet>
<ID>15</ID>
<GivenID>14</GivenID>
<Level>36</Level>
<Armor>100</Armor>
<EvasionRating>800</EvasionRating>
<EnergyShield>0</EnergyShield>
<RequiredStr>0</RequiredStr>
<RequiredDex>9</RequiredDex>
<RequiredInt>0</RequiredInt>
<ItemName>헬멧19</ItemName>
</Helmet>
<Helmet>
<ID>16</ID>
<GivenID>15</GivenID>
<Level>42</Level>
<Armor>100</Armor>
<EvasionRating>500</EvasionRating>
<EnergyShield>400</EnergyShield>
<RequiredStr>0</RequiredStr>
<RequiredDex>0</RequiredDex>
<RequiredInt>9</RequiredInt>
<ItemName>헬멧20</ItemName>
</Helmet>
<Helmet>
<ID>17</ID>
<GivenID>16</GivenID>
<Level>49</Level>
<Armor>800</Armor>
<EvasionRating>0</EvasionRating>
<EnergyShield>400</EnergyShield>
<RequiredStr>0</RequiredStr>
<RequiredDex>0</RequiredDex>
<RequiredInt>8</RequiredInt>
<ItemName>헬멧23</ItemName>
</Helmet>
<Helmet>
<ID>18</ID>
<GivenID>17</GivenID>
<Level>56</Level>
<Armor>0</Armor>
<EvasionRating>1200</EvasionRating>
<EnergyShield>0</EnergyShield>
<RequiredStr>0</RequiredStr>
<RequiredDex>0</RequiredDex>
<RequiredInt>7</RequiredInt>
<ItemName>헬멧24</ItemName>
</Helmet>
<Helmet>
<ID>19</ID>
<GivenID>18</GivenID>
<Level>60</Level>
<Armor>1200</Armor>
<EvasionRating>0</EvasionRating>
<EnergyShield>0</EnergyShield>
<RequiredStr>0</RequiredStr>
<RequiredDex>10</RequiredDex>
<RequiredInt>0</RequiredInt>
<ItemName>헬멧25</ItemName>
</Helmet>
<Helmet>
<ID>20</ID>
<GivenID>19</GivenID>
<Level>62</Level>
<Armor>0</Armor>
<EvasionRating>0</EvasionRating>
<EnergyShield>1200</EnergyShield>
<RequiredStr>11</RequiredStr>
<RequiredDex>0</RequiredDex>
<RequiredInt>0</RequiredInt>
<ItemName>헬멧26</ItemName>
</Helmet>
<Helmet>
<ID>21</ID>
<GivenID>20</GivenID>
<Level>70</Level>
<Armor>1000</Armor>
<EvasionRating>1000</EvasionRating>
<EnergyShield>1000</EnergyShield>
<RequiredStr>0</RequiredStr>
<RequiredDex>0</RequiredDex>
<RequiredInt>12</RequiredInt>
<ItemName>스틸스케일부츠</ItemName>
</Helmet>
</dataroot>
