=== korea-doko/Craft-Proj/Assets/Resources/XML/Mace.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Mace" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="Mace">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="GivenID" index-key="GivenID " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="PrimaryKey" index-key="ID " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAAC/wH+snoq8S5x6ejgRORXnAAAAAMhyr6KT++RAAAAAAAAAAABNAGEA
YwBlAAAAAAAAAJ2tuVH6kQpIiHrDKMqBVwQHAAAAv8B/rJ6KvEuceno4ETkV50kA
RAAAAAAAAACgylZqQLx7S4n41h5LYwjhBwAAAL/Af6yeirxLnHp6OBE5FedHAGkA
dgBlAG4ASQBEAAAAAAAAAHkGD+z2RV1PvSQP0XL0VsYHAAAAv8B/rJ6KvEuceno4
ETkV50wAZQB2AGUAbAAAAAAAAADJII/XUpIBQJwnPFQFIjDrBwAAAL/Af6yeirxL
nHp6OBE5FedSAGUAcQB1AGkAcgBlAGQAUwB0AHIAAAAAAAAATgWHySNETEuKM5fj
VIvpIQcAAAC/wH+snoq8S5x6ejgRORXnUgBlAHEAdQBpAHIAZQBkAEQAZQB4AAAA
AAAAAE1AKlsArSNBhvA3NOkmk6UHAAAAv8B/rJ6KvEuceno4ETkV51IAZQBxAHUA
aQByAGUAZABJAG4AdAAAAAAAAADoguJpOd+vTIqr1lux8zDUBwAAAL/Af6yeirxL
nHp6OBE5FedBAHQAdABhAGMAawBTAHAAZQBlAGQAAAAAAAAAuJHY9XnMDk+u7zcf
cAyDngcAAAC/wH+snoq8S5x6ejgRORXnTQBpAG4ARABhAG0AYQBnAGUAAAAAAAAA
6LaQwyOwnkWqGynNJyjS2gcAAAC/wH+snoq8S5x6ejgRORXnSQB0AGUAbQBOAGEA
bQBlAAAAAAAAAAko1o5mcXFMiabdQ1v47yIHAAAAv8B/rJ6KvEuceno4ETkV500A
YQB4AEQAYQBtAGEAZwBlAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAABQAAAAAA
AAAAAAAAAAAAAAAA
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="95"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="3"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="0"/>
<od:tableProperty name="GUID" type="9" value="v8B/rJ6KvEuceno4ETkV5w==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="ID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="na25UfqRCkiIesMoyoFXBA==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="GivenID" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="oMpWakC8e0uJ+NYeS2MI4Q==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Level" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="eQYP7PZFXU+9JA/RcvRWxg==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="RequiredStr" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="1830"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="ySCP11KSAUCcJzxUBSIw6w==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="RequiredDex" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="1875"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="TgWHySNETEuKM5fjVIvpIQ==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="RequiredInt" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="1740"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="TUAqWwCtI0GG8Dc06SaTpQ==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="AttackSpeed" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="1965"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="6ILiaTnfr0yKq9ZbsfMw1A==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="MinDamage" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="1800"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="uJHY9XnMDk+u7zcfcAyDng==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="ItemName" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="1755"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="10"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="6LaQwyOwnkWqGynNJyjS2g==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="MaxDamage" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2055"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="CSjWjmZxcUyJpt1DW/jvIg==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== korea-doko/Craft-Proj/Assets/Resources/XML/Mace.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Mace.xsd" generated="2017-08-25T14:54:48">
<Mace>
<ID>1</ID>
<GivenID>0</GivenID>
<Level>1</Level>
<RequiredStr>8</RequiredStr>
<RequiredDex>8</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>145</AttackSpeed>
<MinDamage>4</MinDamage>
<ItemName>메이스1</ItemName>
<MaxDamage>10</MaxDamage>
</Mace>
<Mace>
<ID>2</ID>
<GivenID>1</GivenID>
<Level>5</Level>
<RequiredStr>14</RequiredStr>
<RequiredDex>14</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>140</AttackSpeed>
<MinDamage>7</MinDamage>
<ItemName>메이스12</ItemName>
<MaxDamage>15</MaxDamage>
</Mace>
<Mace>
<ID>3</ID>
<GivenID>2</GivenID>
<Level>10</Level>
<RequiredStr>18</RequiredStr>
<RequiredDex>26</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>155</AttackSpeed>
<MinDamage>5</MinDamage>
<ItemName>메이스13</ItemName>
<MaxDamage>22</MaxDamage>
</Mace>
<Mace>
<ID>4</ID>
<GivenID>3</GivenID>
<Level>15</Level>
<RequiredStr>30</RequiredStr>
<RequiredDex>30</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>130</AttackSpeed>
<MinDamage>17</MinDamage>
<ItemName>메이스14</ItemName>
<MaxDamage>25</MaxDamage>
</Mace>
<Mace>
<ID>5</ID>
<GivenID>4</GivenID>
<Level>20</Level>
<RequiredStr>41</RequiredStr>
<RequiredDex>35</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>120</AttackSpeed>
<MinDamage>20</MinDamage>
<ItemName>메이스15</ItemName>
<MaxDamage>37</MaxDamage>
</Mace>
<Mace>
<ID>6</ID>
<GivenID>5</GivenID>
<Level>24</Level>
<RequiredStr>44</RequiredStr>
<RequiredDex>44</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>130</AttackSpeed>
<MinDamage>20</MinDamage>
<ItemName>메이스16</ItemName>
<MaxDamage>38</MaxDamage>
</Mace>
<Mace>
<ID>7</ID>
<GivenID>6</GivenID>
<Level>28</Level>
<RequiredStr>46</RequiredStr>
<RequiredDex>55</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>150</AttackSpeed>
<MinDamage>19</MinDamage>
<ItemName>메이스17</ItemName>
<MaxDamage>33</MaxDamage>
</Mace>
<Mace>
<ID>8</ID>
<GivenID>7</GivenID>
<Level>32</Level>
<RequiredStr>57</RequiredStr>
<RequiredDex>57</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>130</AttackSpeed>
<MinDamage>28</MinDamage>
<ItemName>메이스18</ItemName>
<MaxDamage>54</MaxDamage>
</Mace>
<Mace>
<ID>9</ID>
<GivenID>8</GivenID>
<Level>34</Level>
<RequiredStr>64</RequiredStr>
<RequiredDex>64</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>115</AttackSpeed>
<MinDamage>25</MinDamage>
<ItemName>메이스19</ItemName>
<MaxDamage>60</MaxDamage>
</Mace>
<Mace>
<ID>10</ID>
<GivenID>9</GivenID>
<Level>35</Level>
<RequiredStr>62</RequiredStr>
<RequiredDex>62</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>130</AttackSpeed>
<MinDamage>13</MinDamage>
<ItemName>메이스110</ItemName>
<MaxDamage>53</MaxDamage>
</Mace>
<Mace>
<ID>11</ID>
<GivenID>10</GivenID>
<Level>38</Level>
<RequiredStr>55</RequiredStr>
<RequiredDex>79</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>155</AttackSpeed>
<MinDamage>37</MinDamage>
<ItemName>메이스111</ItemName>
<MaxDamage>53</MaxDamage>
</Mace>
<Mace>
<ID>12</ID>
<GivenID>11</GivenID>
<Level>41</Level>
<RequiredStr>72</RequiredStr>
<RequiredDex>72</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>130</AttackSpeed>
<MinDamage>38</MinDamage>
<ItemName>메이스112</ItemName>
<MaxDamage>53</MaxDamage>
</Mace>
<Mace>
<ID>13</ID>
<GivenID>12</GivenID>
<Level>44</Level>
<RequiredStr>83</RequiredStr>
<RequiredDex>70</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>120</AttackSpeed>
<MinDamage>36</MinDamage>
<ItemName>메이스113</ItemName>
<MaxDamage>70</MaxDamage>
</Mace>
<Mace>
<ID>14</ID>
<GivenID>13</GivenID>
<Level>47</Level>
<RequiredStr>81</RequiredStr>
<RequiredDex>81</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>130</AttackSpeed>
<MinDamage>34</MinDamage>
<ItemName>메이스114</ItemName>
<MaxDamage>66</MaxDamage>
</Mace>
<Mace>
<ID>15</ID>
<GivenID>14</GivenID>
<Level>50</Level>
<RequiredStr>78</RequiredStr>
<RequiredDex>94</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>150</AttackSpeed>
<MinDamage>30</MinDamage>
<ItemName>메이스115</ItemName>
<MaxDamage>55</MaxDamage>
</Mace>
<Mace>
<ID>16</ID>
<GivenID>15</GivenID>
<Level>53</Level>
<RequiredStr>91</RequiredStr>
<RequiredDex>91</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>130</AttackSpeed>
<MinDamage>44</MinDamage>
<ItemName>메이스116</ItemName>
<MaxDamage>86</MaxDamage>
</Mace>
<Mace>
<ID>17</ID>
<GivenID>16</GivenID>
<Level>55</Level>
<RequiredStr>99</RequiredStr>
<RequiredDex>99</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>115</AttackSpeed>
<MinDamage>39</MinDamage>
<ItemName>메이스117</ItemName>
<MaxDamage>94</MaxDamage>
</Mace>
<Mace>
<ID>18</ID>
<GivenID>17</GivenID>
<Level>56</Level>
<RequiredStr>96</RequiredStr>
<RequiredDex>96</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>130</AttackSpeed>
<MinDamage>20</MinDamage>
<ItemName>메이스118</ItemName>
<MaxDamage>83</MaxDamage>
</Mace>
<Mace>
<ID>19</ID>
<GivenID>18</GivenID>
<Level>58</Level>
<RequiredStr>81</RequiredStr>
<RequiredDex>117</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>155</AttackSpeed>
<MinDamage>54</MinDamage>
<ItemName>메이스119</ItemName>
<MaxDamage>80</MaxDamage>
</Mace>
<Mace>
<ID>20</ID>
<GivenID>19</GivenID>
<Level>60</Level>
<RequiredStr>113</RequiredStr>
<RequiredDex>113</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>130</AttackSpeed>
<MinDamage>53</MinDamage>
<ItemName>메이스120</ItemName>
<MaxDamage>78</MaxDamage>
</Mace>
<Mace>
<ID>21</ID>
<GivenID>20</GivenID>
<Level>62</Level>
<RequiredStr>122</RequiredStr>
<RequiredDex>104</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>120</AttackSpeed>
<MinDamage>46</MinDamage>
<ItemName>메이스121</ItemName>
<MaxDamage>98</MaxDamage>
</Mace>
<Mace>
<ID>22</ID>
<GivenID>21</GivenID>
<Level>64</Level>
<RequiredStr>113</RequiredStr>
<RequiredDex>113</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>130</AttackSpeed>
<MinDamage>41</MinDamage>
<ItemName>미드나잇 블레이드</ItemName>
<MaxDamage>86</MaxDamage>
</Mace>
</dataroot>
