=== korea-doko/Craft-Proj/Assets/Resources/XML/Sword.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Sword" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="Sword">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="GivenID" index-key="GivenID " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="PrimaryKey" index-key="ID " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
<od:tableProperty name="GUID" type="9" value="heGFN07ZNkyFR7Qa5hVRzw==
"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAACF4YU3Ttk2TIVHtBrmFVHPAAAAAM+iPIlC++RAAAAAAAAAAABPAG4A
ZQBIAGEAbgBkAGUAZABTAHcAbwByAGQAAAAAAAAA4K0JbNnkDkO30fGNm/gW3AcA
AACF4YU3Ttk2TIVHtBrmFVHPSQBEAAAAAAAAAL9VFpRg5npOj0rzTbEj+8AHAAAA
heGFN07ZNkyFR7Qa5hVRz0cAaQB2AGUAbgBJAEQAAAAAAAAAZ1DLHG6Sqk6iqSzR
+mJmOQcAAACF4YU3Ttk2TIVHtBrmFVHPTABlAHYAZQBsAAAAAAAAAMGNLvqk57BL
lSaNrhh9sIIHAAAAheGFN07ZNkyFR7Qa5hVRz1IAZQBxAHUAaQByAGUAZABTAHQA
cgAAAAAAAAClIr4O3V64SqxRdlKkSiyBBwAAAIXhhTdO2TZMhUe0GuYVUc9SAGUA
cQB1AGkAcgBlAGQARABlAHgAAAAAAAAAFmshrLT5KUyzfGsYiAELwwcAAACF4YU3
Ttk2TIVHtBrmFVHPUgBlAHEAdQBpAHIAZQBkAEkAbgB0AAAAAAAAABnL1KnowppD
hImRN48+FP8HAAAAheGFN07ZNkyFR7Qa5hVRz0EAdAB0AGEAYwBrAFMAcABlAGUA
ZAAAAAAAAAATqeAhjhIWS7QjSSFw33leBwAAAIXhhTdO2TZMhUe0GuYVUc9NAGkA
bgBEAGEAbQBhAGcAZQAAAAAAAAAACWpx/YetRKb8W2oot9MKBwAAAIXhhTdO2TZM
hUe0GuYVUc9JAHQAZQBtAE4AYQBtAGUAAAAAAAAAiqFYYN4f3kefFJlH0KrRHgcA
AACF4YU3Ttk2TIVHtBrmFVHPTQBhAHgARABhAG0AYQBnAGUAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAwAAAAFAAAAAAAAAAAAAAAAAAAAAAA=
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="95"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="3"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="ID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="4K0JbNnkDkO30fGNm/gW3A==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="GivenID" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="v1UWlGDmek6PSvNNsSP7wA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="2"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Level" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="Z1DLHG6Sqk6iqSzR+mJmOQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="4"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="RequiredStr" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="wY0u+qTnsEuVJo2uGH2wgg==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="1830"/>
<od:fieldProperty name="ColumnOrder" type="3" value="8"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="RequiredDex" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="pSK+Dt1euEqsUXZSpEosgQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="1875"/>
<od:fieldProperty name="ColumnOrder" type="3" value="9"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="RequiredInt" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="FmshrLT5KUyzfGsYiAELww==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="1740"/>
<od:fieldProperty name="ColumnOrder" type="3" value="10"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="AttackSpeed" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="GcvUqejCmkOEiZE3jz4U/w==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="1965"/>
<od:fieldProperty name="ColumnOrder" type="3" value="7"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="MinDamage" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="E6ngIY4SFku0I0khcN95Xg==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="1800"/>
<od:fieldProperty name="ColumnOrder" type="3" value="5"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="ItemName" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="AAlqcf2HrUSm/FtqKLfTCg==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="1755"/>
<od:fieldProperty name="ColumnOrder" type="3" value="3"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="10"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="MaxDamage" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="iqFYYN4f3kefFJlH0KrRHg==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="2055"/>
<od:fieldProperty name="ColumnOrder" type="3" value="6"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== korea-doko/Craft-Proj/Assets/Resources/XML/Sword.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Sword.xsd" generated="2017-08-25T14:35:52">
<Sword>
<ID>1</ID>
<GivenID>0</GivenID>
<Level>1</Level>
<RequiredStr>8</RequiredStr>
<RequiredDex>8</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>145</AttackSpeed>
<MinDamage>4</MinDamage>
<ItemName>러스티드 소드</ItemName>
<MaxDamage>10</MaxDamage>
</Sword>
<Sword>
<ID>2</ID>
<GivenID>1</GivenID>
<Level>5</Level>
<RequiredStr>14</RequiredStr>
<RequiredDex>14</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>140</AttackSpeed>
<MinDamage>7</MinDamage>
<ItemName>코퍼 소드</ItemName>
<MaxDamage>15</MaxDamage>
</Sword>
<Sword>
<ID>3</ID>
<GivenID>2</GivenID>
<Level>10</Level>
<RequiredStr>18</RequiredStr>
<RequiredDex>26</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>155</AttackSpeed>
<MinDamage>5</MinDamage>
<ItemName>샤브르</ItemName>
<MaxDamage>22</MaxDamage>
</Sword>
<Sword>
<ID>4</ID>
<GivenID>3</GivenID>
<Level>15</Level>
<RequiredStr>30</RequiredStr>
<RequiredDex>30</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>130</AttackSpeed>
<MinDamage>17</MinDamage>
<ItemName>브로드 소드</ItemName>
<MaxDamage>25</MaxDamage>
</Sword>
<Sword>
<ID>5</ID>
<GivenID>4</GivenID>
<Level>20</Level>
<RequiredStr>41</RequiredStr>
<RequiredDex>35</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>120</AttackSpeed>
<MinDamage>20</MinDamage>
<ItemName>워 소드</ItemName>
<MaxDamage>37</MaxDamage>
</Sword>
<Sword>
<ID>6</ID>
<GivenID>5</GivenID>
<Level>24</Level>
<RequiredStr>44</RequiredStr>
<RequiredDex>44</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>130</AttackSpeed>
<MinDamage>20</MinDamage>
<ItemName>에이션트 소드</ItemName>
<MaxDamage>38</MaxDamage>
</Sword>
<Sword>
<ID>7</ID>
<GivenID>6</GivenID>
<Level>28</Level>
<RequiredStr>46</RequiredStr>
<RequiredDex>55</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>150</AttackSpeed>
<MinDamage>19</MinDamage>
<ItemName>엘레간트 소드</ItemName>
<MaxDamage>33</MaxDamage>
</Sword>
<Sword>
<ID>8</ID>
<GivenID>7</GivenID>
<Level>32</Level>
<RequiredStr>57</RequiredStr>
<RequiredDex>57</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>130</AttackSpeed>
<MinDamage>28</MinDamage>
<ItemName>더스크 블레이드</ItemName>
<MaxDamage>54</MaxDamage>
</Sword>
<Sword>
<ID>9</ID>
<GivenID>8</GivenID>
<Level>34</Level>
<RequiredStr>64</RequiredStr>
<RequiredDex>64</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>115</AttackSpeed>
<MinDamage>25</MinDamage>
<ItemName>훅 소드</ItemName>
<MaxDamage>60</MaxDamage>
</Sword>
<Sword>
<ID>10</ID>
<GivenID>9</GivenID>
<Level>35</Level>
<RequiredStr>62</RequiredStr>
<RequiredDex>62</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>130</AttackSpeed>
<MinDamage>13</MinDamage>
<ItemName>베리스사이트 블레이드</ItemName>
<MaxDamage>53</MaxDamage>
</Sword>
<Sword>
<ID>11</ID>
<GivenID>10</GivenID>
<Level>38</Level>
<RequiredStr>55</RequiredStr>
<RequiredDex>79</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>155</AttackSpeed>
<MinDamage>37</MinDamage>
<ItemName>커틀라스</ItemName>
<MaxDamage>53</MaxDamage>
</Sword>
<Sword>
<ID>12</ID>
<GivenID>11</GivenID>
<Level>41</Level>
<RequiredStr>72</RequiredStr>
<RequiredDex>72</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>130</AttackSpeed>
<MinDamage>38</MinDamage>
<ItemName>바셀라드</ItemName>
<MaxDamage>53</MaxDamage>
</Sword>
<Sword>
<ID>13</ID>
<GivenID>12</GivenID>
<Level>44</Level>
<RequiredStr>83</RequiredStr>
<RequiredDex>70</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>120</AttackSpeed>
<MinDamage>36</MinDamage>
<ItemName>배틀 소드</ItemName>
<MaxDamage>70</MaxDamage>
</Sword>
<Sword>
<ID>14</ID>
<GivenID>13</GivenID>
<Level>47</Level>
<RequiredStr>81</RequiredStr>
<RequiredDex>81</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>130</AttackSpeed>
<MinDamage>34</MinDamage>
<ItemName>엘더 소드</ItemName>
<MaxDamage>66</MaxDamage>
</Sword>
<Sword>
<ID>15</ID>
<GivenID>14</GivenID>
<Level>50</Level>
<RequiredStr>78</RequiredStr>
<RequiredDex>94</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>150</AttackSpeed>
<MinDamage>30</MinDamage>
<ItemName>그레이스풀 소드</ItemName>
<MaxDamage>55</MaxDamage>
</Sword>
<Sword>
<ID>16</ID>
<GivenID>15</GivenID>
<Level>53</Level>
<RequiredStr>91</RequiredStr>
<RequiredDex>91</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>130</AttackSpeed>
<MinDamage>44</MinDamage>
<ItemName>트와일라잇 블레이드</ItemName>
<MaxDamage>86</MaxDamage>
</Sword>
<Sword>
<ID>17</ID>
<GivenID>16</GivenID>
<Level>55</Level>
<RequiredStr>99</RequiredStr>
<RequiredDex>99</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>115</AttackSpeed>
<MinDamage>39</MinDamage>
<ItemName>그래플러</ItemName>
<MaxDamage>94</MaxDamage>
</Sword>
<Sword>
<ID>18</ID>
<GivenID>17</GivenID>
<Level>56</Level>
<RequiredStr>96</RequiredStr>
<RequiredDex>96</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>130</AttackSpeed>
<MinDamage>20</MinDamage>
<ItemName>커세어 블레이드</ItemName>
<MaxDamage>83</MaxDamage>
</Sword>
<Sword>
<ID>19</ID>
<GivenID>18</GivenID>
<Level>58</Level>
<RequiredStr>81</RequiredStr>
<RequiredDex>117</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>155</AttackSpeed>
<MinDamage>54</MinDamage>
<ItemName>리전 소드</ItemName>
<MaxDamage>80</MaxDamage>
</Sword>
<Sword>
<ID>20</ID>
<GivenID>19</GivenID>
<Level>60</Level>
<RequiredStr>113</RequiredStr>
<RequiredDex>113</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>130</AttackSpeed>
<MinDamage>53</MinDamage>
<ItemName>바알 블레이드</ItemName>
<MaxDamage>78</MaxDamage>
</Sword>
<Sword>
<ID>21</ID>
<GivenID>20</GivenID>
<Level>62</Level>
<RequiredStr>122</RequiredStr>
<RequiredDex>104</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>120</AttackSpeed>
<MinDamage>46</MinDamage>
<ItemName>이터널 소드</ItemName>
<MaxDamage>98</MaxDamage>
</Sword>
<Sword>
<ID>22</ID>
<GivenID>21</GivenID>
<Level>64</Level>
<RequiredStr>113</RequiredStr>
<RequiredDex>113</RequiredDex>
<RequiredInt>0</RequiredInt>
<AttackSpeed>130</AttackSpeed>
<MinDamage>41</MinDamage>
<ItemName>미드나잇 블레이드</ItemName>
<MaxDamage>86</MaxDamage>
</Sword>
</dataroot>
